_TOOL_NAME_MAP: dict[str, str] = {
    "BashTool": "bash",
    "Bash": "bash",
    "ReadTool": "read",
    "Read": "read",
    "WriteTool": "write",
    "Write": "write",
    "EditTool": "edit",
    "Edit": "edit",
    "GrepTool": "grep",
    "Grep": "grep",
    "GlobTool": "glob",
    "Glob": "glob",
    "ListTool": "list",
    "List": "list",
    "TaskTool": "task",
    "Task": "task",
    "WebFetchTool": "webfetch",
    "WebFetch": "webfetch",
    "WebSearchTool": "websearch",
    "WebSearch": "websearch",
    "CodeSearchTool": "codesearch",
    "CodeSearch": "codesearch",
    "TodoWrite": "todowrite",
    "TodoWriteTool": "todowrite",
    "QuestionTool": "question",
    "Question": "question",
    "ApplyPatch": "apply_patch",
    "ApplyPatchTool": "apply_patch",
    "SkillTool": "skill",
    "Skill": "skill",
}


def normalize_tool_name(name: str) -> str:
    return _TOOL_NAME_MAP.get(name, name.lower())
