/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Create_userRouteImport } from './routes/create_user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvoIndexRouteImport } from './routes/convo/index'
import { Route as ConvoConvoIdRouteImport } from './routes/convo/$ConvoId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Create_userRoute = Create_userRouteImport.update({
  id: '/create_user',
  path: '/create_user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvoIndexRoute = ConvoIndexRouteImport.update({
  id: '/convo/',
  path: '/convo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvoConvoIdRoute = ConvoConvoIdRouteImport.update({
  id: '/convo/$ConvoId',
  path: '/convo/$ConvoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create_user': typeof Create_userRoute
  '/login': typeof LoginRoute
  '/convo/$ConvoId': typeof ConvoConvoIdRoute
  '/convo': typeof ConvoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create_user': typeof Create_userRoute
  '/login': typeof LoginRoute
  '/convo/$ConvoId': typeof ConvoConvoIdRoute
  '/convo': typeof ConvoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create_user': typeof Create_userRoute
  '/login': typeof LoginRoute
  '/convo/$ConvoId': typeof ConvoConvoIdRoute
  '/convo/': typeof ConvoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create_user' | '/login' | '/convo/$ConvoId' | '/convo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create_user' | '/login' | '/convo/$ConvoId' | '/convo'
  id:
    | '__root__'
    | '/'
    | '/create_user'
    | '/login'
    | '/convo/$ConvoId'
    | '/convo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Create_userRoute: typeof Create_userRoute
  LoginRoute: typeof LoginRoute
  ConvoConvoIdRoute: typeof ConvoConvoIdRoute
  ConvoIndexRoute: typeof ConvoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create_user': {
      id: '/create_user'
      path: '/create_user'
      fullPath: '/create_user'
      preLoaderRoute: typeof Create_userRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convo/': {
      id: '/convo/'
      path: '/convo'
      fullPath: '/convo'
      preLoaderRoute: typeof ConvoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convo/$ConvoId': {
      id: '/convo/$ConvoId'
      path: '/convo/$ConvoId'
      fullPath: '/convo/$ConvoId'
      preLoaderRoute: typeof ConvoConvoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Create_userRoute: Create_userRoute,
  LoginRoute: LoginRoute,
  ConvoConvoIdRoute: ConvoConvoIdRoute,
  ConvoIndexRoute: ConvoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
