"""change attached_files to jsonb

Revision ID: ffef6ad4becb
Revises: 
Create Date: 2026-01-28 19:51:36.063448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffef6ad4becb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('source_id', sa.String(length=26), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('origin_path', sa.String(length=2048), nullable=False),
    sa.Column('origin_type', sa.String(length=50), nullable=False),
    sa.Column('unique_id', sa.String(length=100), nullable=False),
    sa.Column('times_accessed', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_summary', sa.Text(), nullable=False),
    sa.Column('summary_embedding', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_sources_source_hash'), 'sources', ['source_hash'], unique=True)
    op.create_index(op.f('ix_sources_unique_id'), 'sources', ['unique_id'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=400), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chunks',
    sa.Column('chunk_id', sa.String(length=26), nullable=False),
    sa.Column('source_id', sa.String(length=26), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('start_index', sa.Integer(), nullable=False),
    sa.Column('end_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_index > start_index', name='check_end_after_start'),
    sa.CheckConstraint('start_index >= 0', name='check_start_index_non_negative'),
    sa.CheckConstraint('token_count > 0', name='check_token_count_positive'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_chunks_source_id', 'chunks', ['source_id'], unique=False)
    op.create_table('user_tool_configs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_configs_system_defaults', 'user_tool_configs', ['is_system_default', 'category'], unique=False)
    op.create_index('ix_tool_configs_user_category', 'user_tool_configs', ['user_id', 'category'], unique=False)
    op.create_index(op.f('ix_user_tool_configs_user_id'), 'user_tool_configs', ['user_id'], unique=False)
    op.create_index('uix_system_default_category', 'user_tool_configs', ['category'], unique=True, postgresql_where=sa.text('is_system_default = true'))
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('archived_convos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_user_workspace')
    )
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)
    op.create_table('convos',
    sa.Column('convo_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('workspace_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('convo_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('convo_id')
    )
    op.create_index('ix_convo_user_workspace', 'convos', ['user_id', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_convos_convo_id'), 'convos', ['convo_id'], unique=False)
    op.create_table('source_workspace_association',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'workspace_id')
    )
    op.create_table('config_assignments',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tool_config_id', sa.String(length=26), nullable=False),
    sa.Column('workspace_id', sa.String(length=26), nullable=True),
    sa.Column('convo_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(workspace_id IS NOT NULL AND convo_id IS NULL) OR (workspace_id IS NULL AND convo_id IS NOT NULL)', name='check_exactly_one_scope'),
    sa.ForeignKeyConstraint(['convo_id'], ['convos.convo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_config_id'], ['user_tool_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_config', 'config_assignments', ['tool_config_id'], unique=False)
    op.create_index('ix_assignments_convo_role', 'config_assignments', ['convo_id', 'role'], unique=False)
    op.create_index('ix_assignments_workspace_role', 'config_assignments', ['workspace_id', 'role'], unique=False)
    op.create_index('uix_convo_role', 'config_assignments', ['convo_id', 'role'], unique=True, postgresql_where=sa.text('convo_id IS NOT NULL'))
    op.create_index('uix_workspace_role', 'config_assignments', ['workspace_id', 'role'], unique=True, postgresql_where=sa.text('workspace_id IS NOT NULL'))
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=26), nullable=False),
    sa.Column('convo_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attached_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attached_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chat_metadata', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system', 'tool')", name='check_valid_role'),
    sa.ForeignKeyConstraint(['convo_id'], ['convos.convo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.message_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_messages_convo_created', 'messages', ['convo_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index('ix_messages_convo_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uix_workspace_role', table_name='config_assignments', postgresql_where=sa.text('workspace_id IS NOT NULL'))
    op.drop_index('uix_convo_role', table_name='config_assignments', postgresql_where=sa.text('convo_id IS NOT NULL'))
    op.drop_index('ix_assignments_workspace_role', table_name='config_assignments')
    op.drop_index('ix_assignments_convo_role', table_name='config_assignments')
    op.drop_index('ix_assignments_config', table_name='config_assignments')
    op.drop_table('config_assignments')
    op.drop_table('source_workspace_association')
    op.drop_index(op.f('ix_convos_convo_id'), table_name='convos')
    op.drop_index('ix_convo_user_workspace', table_name='convos')
    op.drop_table('convos')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('uix_system_default_category', table_name='user_tool_configs', postgresql_where=sa.text('is_system_default = true'))
    op.drop_index(op.f('ix_user_tool_configs_user_id'), table_name='user_tool_configs')
    op.drop_index('ix_tool_configs_user_category', table_name='user_tool_configs')
    op.drop_index('ix_tool_configs_system_defaults', table_name='user_tool_configs')
    op.drop_table('user_tool_configs')
    op.drop_index('ix_chunks_source_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('users')
    op.drop_index(op.f('ix_sources_unique_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_hash'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
