from backend.src.domain.exceptions.exceptions import (
    # Base Exception
    FOSRAError,
    # Infrastructure & Resources
    InfrastructureError,
    InitializationError,
    ServiceUnavailableError,
    LLMProviderError,
    LLMRateLimitError,
    # Security & Access Control
    SecurityError,
    TenantContextError,
    WorkspaceAccessDenied,
    QuotaExceededError,
    # Processing & Ingestion
    ProcessingError,
    ParsingError,
    UnsupportedFileTypeError,
    EmbeddingError,
    ChunkingError,
    ContextWindowError,
    # Storage & Retrieval
    StorageError,
    VectorStorageError,
    VectorRetrievalError,
    FileStorageError,
    DatabaseError,
    UserStorageError,
    UserRetrievalError,
    UserExistenceError,
    WorkspaceStorageError,
    WorkspaceRetrievalError,
    WorkspaceExistenceError,
    ConvoStorageError,
    ConvoRetrievalError,
    CollectionNotFoundError,
    EmptyRetrievalError,
    # Convo & Streaming
    ConvoError,
    SessionNotFoundError,
    StateTransitionError,
    ConvoStateError,
    ConvoValidationError,
    StreamingError,
    StreamConnectionError,
    StreamProcessingError,
    # LLM Operations
    LLMError,
    LLMValidationError,
    LLMConfigurationError,
    # Embedder
    EmbedderError,
    EmbedderNotFoundError,
    EmbedderInitializationError,
    EmbeddingOperationError,
    APIKeyMissingError,
    ModelNotInitializedError,
    # Parser
    ParserError,
    ParserNotFoundError,
    ParserInitializationError,
    ParsingOperationError,
    ParserTimeoutError,
    UnsupportedDocumentTypeError,
    ParserDependencyError,
    InvalidDocumentError,
    # File Storage Backend
    StorageBackendNotFoundError,
    StorageBackendInitializationError,
    FileNotFoundError,
    FileReadError,
    FileListError,
    InvalidPathError,
    UnsupportedBackendError,
    StorageCredentialsError,
    StorageConnectionError,
    # Reranker
    RerankerError,
    RerankerNotFoundError,
    RerankerInitializationError,
    RerankingOperationError,
    RerankerTimeoutError,
    RerankerDependencyError,
    RerankerAPIConfigError,
    InvalidDocumentListError,
    # Query & Search
    QueryError,
    QueryExpansionError,
    QueryReformulationError,
    RetrievalError,
    VectorSearchError,
    ChunkRetrievalError,
    SourceRetrievalError,
    RerankingError,
    FusionError,
    MetadataFilterError,
    # RAG
    RAGError,
    ContextRetrievalError,
    MessageStorageError,
    # CONFIG:
    ConfigExistenceError,
    ConfigRetrievalError,
    ConfigStorageError,
)

__all__ = [
    # Base Exception
    "FOSRAError",
    # Infrastructure & Resources
    "InfrastructureError",
    "InitializationError",
    "ServiceUnavailableError",
    "LLMProviderError",
    "LLMRateLimitError",
    # Security & Access Control
    "SecurityError",
    "TenantContextError",
    "WorkspaceAccessDenied",
    "QuotaExceededError",
    # Processing & Ingestion
    "ProcessingError",
    "ParsingError",
    "UnsupportedFileTypeError",
    "EmbeddingError",
    "ChunkingError",
    "ContextWindowError",
    # Storage & Retrieval
    "StorageError",
    "VectorStorageError",
    "VectorRetrievalError",
    "FileStorageError",
    "DatabaseError",
    "UserStorageError",
    "UserRetrievalError",
    "UserExistenceError",
    "WorkspaceStorageError",
    "WorkspaceRetrievalError",
    "WorkspaceExistenceError",
    "ConvoStorageError",
    "ConvoRetrievalError",
    "CollectionNotFoundError",
    "EmptyRetrievalError",
    # Convo & Streaming
    "ConvoError",
    "SessionNotFoundError",
    "StateTransitionError",
    "ConvoStateError",
    "ConvoValidationError",
    "StreamingError",
    "StreamConnectionError",
    "StreamProcessingError",
    # LLM Operations
    "LLMError",
    "LLMValidationError",
    "LLMConfigurationError",
    # Embedder
    "EmbedderError",
    "EmbedderNotFoundError",
    "EmbedderInitializationError",
    "EmbeddingOperationError",
    "APIKeyMissingError",
    "ModelNotInitializedError",
    # Parser
    "ParserError",
    "ParserNotFoundError",
    "ParserInitializationError",
    "ParsingOperationError",
    "ParserTimeoutError",
    "UnsupportedDocumentTypeError",
    "ParserDependencyError",
    "InvalidDocumentError",
    # File Storage Backend
    "StorageBackendNotFoundError",
    "StorageBackendInitializationError",
    "FileNotFoundError",
    "FileReadError",
    "FileListError",
    "InvalidPathError",
    "UnsupportedBackendError",
    "StorageCredentialsError",
    "StorageConnectionError",
    # Reranker
    "RerankerError",
    "RerankerNotFoundError",
    "RerankerInitializationError",
    "RerankingOperationError",
    "RerankerTimeoutError",
    "RerankerDependencyError",
    "RerankerAPIConfigError",
    "InvalidDocumentListError",
    # Query & Search
    "QueryError",
    "QueryExpansionError",
    "QueryReformulationError",
    "RetrievalError",
    "VectorSearchError",
    "ChunkRetrievalError",
    "SourceRetrievalError",
    "RerankingError",
    "FusionError",
    "MetadataFilterError",
    # RAG
    "RAGError",
    "ContextRetrievalError",
    "MessageStorageError",
    # CONFIG:
    "ConfigExistenceError",
    "ConfigRetrievalError",
    "ConfigStorageError",
]
