// Stub for @/lsp/language

export const LANGUAGE_EXTENSIONS: Record<string, string[]> = {
  typescript: ["ts", "tsx"],
  javascript: ["js", "jsx", "mjs", "cjs"],
  python: ["py"],
  rust: ["rs"],
  go: ["go"],
  java: ["java"],
  ruby: ["rb"],
  php: ["php"],
  c: ["c", "h"],
  cpp: ["cpp", "cc", "cxx", "hpp", "hxx"],
  csharp: ["cs"],
  swift: ["swift"],
  kotlin: ["kt", "kts"],
  scala: ["scala"],
  html: ["html", "htm"],
  css: ["css", "scss", "sass", "less"],
  json: ["json"],
  yaml: ["yaml", "yml"],
  markdown: ["md", "markdown"],
  shell: ["sh", "bash", "zsh"],
  sql: ["sql"],
  dockerfile: ["dockerfile", "Dockerfile"],
  toml: ["toml"],
  xml: ["xml", "svg"],
  svelte: ["svelte"],
  vue: ["vue"],
  solid: ["tsx"],
}